//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("eStoreDBModel", "FK_CustHasOrder", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eStoreDataObjects.Customer), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eStoreDataObjects.Order), true)]
[assembly: EdmRelationshipAttribute("eStoreDBModel", "FK_ItemIsProduct", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eStoreDataObjects.Product), "OrderLineitems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eStoreDataObjects.OrderLineitem), true)]
[assembly: EdmRelationshipAttribute("eStoreDBModel", "FK_OrderHasItems", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eStoreDataObjects.Order), "OrderLineitems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eStoreDataObjects.OrderLineitem), true)]

#endregion

namespace eStoreDataObjects
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class eStoreDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new eStoreDBEntities object using the connection string found in the 'eStoreDBEntities' section of the application configuration file.
        /// </summary>
        public eStoreDBEntities() : base("name=eStoreDBEntities", "eStoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new eStoreDBEntities object.
        /// </summary>
        public eStoreDBEntities(string connectionString) : base(connectionString, "eStoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new eStoreDBEntities object.
        /// </summary>
        public eStoreDBEntities(EntityConnection connection) : base(connection, "eStoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Branch> Branches
        {
            get
            {
                if ((_Branches == null))
                {
                    _Branches = base.CreateObjectSet<Branch>("Branches");
                }
                return _Branches;
            }
        }
        private ObjectSet<Branch> _Branches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderLineitem> OrderLineitems
        {
            get
            {
                if ((_OrderLineitems == null))
                {
                    _OrderLineitems = base.CreateObjectSet<OrderLineitem>("OrderLineitems");
                }
                return _OrderLineitems;
            }
        }
        private ObjectSet<OrderLineitem> _OrderLineitems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Branches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBranches(Branch branch)
        {
            base.AddObject("Branches", branch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderLineitems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderLineitems(OrderLineitem orderLineitem)
        {
            base.AddObject("OrderLineitems", orderLineitem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="oid">No Metadata Documentation available.</param>
        /// <param name="cid">No Metadata Documentation available.</param>
        public ObjectResult<SingleOrderDetails> pSingleOrderDetails(Nullable<global::System.Int32> oid, Nullable<global::System.Int32> cid)
        {
            ObjectParameter oidParameter;
            if (oid.HasValue)
            {
                oidParameter = new ObjectParameter("oid", oid);
            }
            else
            {
                oidParameter = new ObjectParameter("oid", typeof(global::System.Int32));
            }
    
            ObjectParameter cidParameter;
            if (cid.HasValue)
            {
                cidParameter = new ObjectParameter("cid", cid);
            }
            else
            {
                cidParameter = new ObjectParameter("cid", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<SingleOrderDetails>("pSingleOrderDetails", oidParameter, cidParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="latitude">No Metadata Documentation available.</param>
        /// <param name="longitude">No Metadata Documentation available.</param>
        public ObjectResult<GetThreeClosestBranches> pGetThreeClosestBranches(Nullable<global::System.Double> latitude, Nullable<global::System.Double> longitude)
        {
            ObjectParameter latitudeParameter;
            if (latitude.HasValue)
            {
                latitudeParameter = new ObjectParameter("Latitude", latitude);
            }
            else
            {
                latitudeParameter = new ObjectParameter("Latitude", typeof(global::System.Double));
            }
    
            ObjectParameter longitudeParameter;
            if (longitude.HasValue)
            {
                longitudeParameter = new ObjectParameter("Longitude", longitude);
            }
            else
            {
                longitudeParameter = new ObjectParameter("Longitude", typeof(global::System.Double));
            }
    
            return base.ExecuteFunction<GetThreeClosestBranches>("pGetThreeClosestBranches", latitudeParameter, longitudeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="cid">No Metadata Documentation available.</param>
        public ObjectResult<SingleOrderDetails> pAllOrderDetails(Nullable<global::System.Int32> cid)
        {
            ObjectParameter cidParameter;
            if (cid.HasValue)
            {
                cidParameter = new ObjectParameter("cid", cid);
            }
            else
            {
                cidParameter = new ObjectParameter("cid", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<SingleOrderDetails>("pAllOrderDetails", cidParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="cid">No Metadata Documentation available.</param>
        public ObjectResult<AllCustomerInfo> pAllCustomerInfo(Nullable<global::System.Int32> cid)
        {
            ObjectParameter cidParameter;
            if (cid.HasValue)
            {
                cidParameter = new ObjectParameter("cid", cid);
            }
            else
            {
                cidParameter = new ObjectParameter("cid", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<AllCustomerInfo>("pAllCustomerInfo", cidParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eStoreDBModel", Name="Branch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Branch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Branch object.
        /// </summary>
        /// <param name="branchNumber">Initial value of the BranchNumber property.</param>
        public static Branch CreateBranch(global::System.Int32 branchNumber)
        {
            Branch branch = new Branch();
            branch.BranchNumber = branchNumber;
            return branch;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BranchNumber
        {
            get
            {
                return _BranchNumber;
            }
            set
            {
                if (_BranchNumber != value)
                {
                    OnBranchNumberChanging(value);
                    ReportPropertyChanging("BranchNumber");
                    _BranchNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BranchNumber");
                    OnBranchNumberChanged();
                }
            }
        }
        private global::System.Int32 _BranchNumber;
        partial void OnBranchNumberChanging(global::System.Int32 value);
        partial void OnBranchNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eStoreDBModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        public static Customer CreateCustomer(global::System.Int32 customerID)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            return customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mailcode
        {
            get
            {
                return _Mailcode;
            }
            set
            {
                OnMailcodeChanging(value);
                ReportPropertyChanging("Mailcode");
                _Mailcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mailcode");
                OnMailcodeChanged();
            }
        }
        private global::System.String _Mailcode;
        partial void OnMailcodeChanging(global::System.String value);
        partial void OnMailcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Creditcardtype
        {
            get
            {
                return _Creditcardtype;
            }
            set
            {
                OnCreditcardtypeChanging(value);
                ReportPropertyChanging("Creditcardtype");
                _Creditcardtype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Creditcardtype");
                OnCreditcardtypeChanged();
            }
        }
        private global::System.String _Creditcardtype;
        partial void OnCreditcardtypeChanging(global::System.String value);
        partial void OnCreditcardtypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eStoreDBModel", "FK_CustHasOrder", "Orders")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("eStoreDBModel.FK_CustHasOrder", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("eStoreDBModel.FK_CustHasOrder", "Orders", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eStoreDBModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="orderDate">Initial value of the OrderDate property.</param>
        /// <param name="shipDate">Initial value of the ShipDate property.</param>
        /// <param name="orderAmount">Initial value of the OrderAmount property.</param>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        public static Order CreateOrder(global::System.Int32 orderID, global::System.DateTime orderDate, global::System.DateTime shipDate, global::System.Decimal orderAmount, global::System.Int32 customerID)
        {
            Order order = new Order();
            order.OrderID = orderID;
            order.OrderDate = orderDate;
            order.ShipDate = shipDate;
            order.OrderAmount = orderAmount;
            order.CustomerID = customerID;
            return order;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ShipDate
        {
            get
            {
                return _ShipDate;
            }
            set
            {
                OnShipDateChanging(value);
                ReportPropertyChanging("ShipDate");
                _ShipDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShipDate");
                OnShipDateChanged();
            }
        }
        private global::System.DateTime _ShipDate;
        partial void OnShipDateChanging(global::System.DateTime value);
        partial void OnShipDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal OrderAmount
        {
            get
            {
                return _OrderAmount;
            }
            set
            {
                OnOrderAmountChanging(value);
                ReportPropertyChanging("OrderAmount");
                _OrderAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderAmount");
                OnOrderAmountChanged();
            }
        }
        private global::System.Decimal _OrderAmount;
        partial void OnOrderAmountChanging(global::System.Decimal value);
        partial void OnOrderAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eStoreDBModel", "FK_CustHasOrder", "Customers")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("eStoreDBModel.FK_CustHasOrder", "Customers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("eStoreDBModel.FK_CustHasOrder", "Customers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("eStoreDBModel.FK_CustHasOrder", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("eStoreDBModel.FK_CustHasOrder", "Customers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eStoreDBModel", "FK_OrderHasItems", "OrderLineitems")]
        public EntityCollection<OrderLineitem> OrderLineitems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderLineitem>("eStoreDBModel.FK_OrderHasItems", "OrderLineitems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderLineitem>("eStoreDBModel.FK_OrderHasItems", "OrderLineitems", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eStoreDBModel", Name="OrderLineitem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderLineitem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderLineitem object.
        /// </summary>
        /// <param name="lineItemID">Initial value of the LineItemID property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="prodcd">Initial value of the Prodcd property.</param>
        /// <param name="qtyOrdered">Initial value of the QtyOrdered property.</param>
        /// <param name="qtySold">Initial value of the QtySold property.</param>
        /// <param name="qtyBackOrdered">Initial value of the QtyBackOrdered property.</param>
        /// <param name="sellingPrice">Initial value of the SellingPrice property.</param>
        public static OrderLineitem CreateOrderLineitem(global::System.Int32 lineItemID, global::System.Int32 orderID, global::System.String prodcd, global::System.Int32 qtyOrdered, global::System.Int32 qtySold, global::System.Int32 qtyBackOrdered, global::System.Decimal sellingPrice)
        {
            OrderLineitem orderLineitem = new OrderLineitem();
            orderLineitem.LineItemID = lineItemID;
            orderLineitem.OrderID = orderID;
            orderLineitem.Prodcd = prodcd;
            orderLineitem.QtyOrdered = qtyOrdered;
            orderLineitem.QtySold = qtySold;
            orderLineitem.QtyBackOrdered = qtyBackOrdered;
            orderLineitem.SellingPrice = sellingPrice;
            return orderLineitem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LineItemID
        {
            get
            {
                return _LineItemID;
            }
            set
            {
                if (_LineItemID != value)
                {
                    OnLineItemIDChanging(value);
                    ReportPropertyChanging("LineItemID");
                    _LineItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LineItemID");
                    OnLineItemIDChanged();
                }
            }
        }
        private global::System.Int32 _LineItemID;
        partial void OnLineItemIDChanging(global::System.Int32 value);
        partial void OnLineItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                OnOrderIDChanging(value);
                ReportPropertyChanging("OrderID");
                _OrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderID");
                OnOrderIDChanged();
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prodcd
        {
            get
            {
                return _Prodcd;
            }
            set
            {
                OnProdcdChanging(value);
                ReportPropertyChanging("Prodcd");
                _Prodcd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prodcd");
                OnProdcdChanged();
            }
        }
        private global::System.String _Prodcd;
        partial void OnProdcdChanging(global::System.String value);
        partial void OnProdcdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QtyOrdered
        {
            get
            {
                return _QtyOrdered;
            }
            set
            {
                OnQtyOrderedChanging(value);
                ReportPropertyChanging("QtyOrdered");
                _QtyOrdered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtyOrdered");
                OnQtyOrderedChanged();
            }
        }
        private global::System.Int32 _QtyOrdered;
        partial void OnQtyOrderedChanging(global::System.Int32 value);
        partial void OnQtyOrderedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QtySold
        {
            get
            {
                return _QtySold;
            }
            set
            {
                OnQtySoldChanging(value);
                ReportPropertyChanging("QtySold");
                _QtySold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtySold");
                OnQtySoldChanged();
            }
        }
        private global::System.Int32 _QtySold;
        partial void OnQtySoldChanging(global::System.Int32 value);
        partial void OnQtySoldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QtyBackOrdered
        {
            get
            {
                return _QtyBackOrdered;
            }
            set
            {
                OnQtyBackOrderedChanging(value);
                ReportPropertyChanging("QtyBackOrdered");
                _QtyBackOrdered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtyBackOrdered");
                OnQtyBackOrderedChanged();
            }
        }
        private global::System.Int32 _QtyBackOrdered;
        partial void OnQtyBackOrderedChanging(global::System.Int32 value);
        partial void OnQtyBackOrderedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SellingPrice
        {
            get
            {
                return _SellingPrice;
            }
            set
            {
                OnSellingPriceChanging(value);
                ReportPropertyChanging("SellingPrice");
                _SellingPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellingPrice");
                OnSellingPriceChanged();
            }
        }
        private global::System.Decimal _SellingPrice;
        partial void OnSellingPriceChanging(global::System.Decimal value);
        partial void OnSellingPriceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eStoreDBModel", "FK_ItemIsProduct", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("eStoreDBModel.FK_ItemIsProduct", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("eStoreDBModel.FK_ItemIsProduct", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("eStoreDBModel.FK_ItemIsProduct", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("eStoreDBModel.FK_ItemIsProduct", "Products", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eStoreDBModel", "FK_OrderHasItems", "Orders")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("eStoreDBModel.FK_OrderHasItems", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("eStoreDBModel.FK_OrderHasItems", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("eStoreDBModel.FK_OrderHasItems", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("eStoreDBModel.FK_OrderHasItems", "Orders", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eStoreDBModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="prodcd">Initial value of the prodcd property.</param>
        /// <param name="prodnam">Initial value of the prodnam property.</param>
        /// <param name="graphic">Initial value of the graphic property.</param>
        /// <param name="costprice">Initial value of the costprice property.</param>
        /// <param name="msrp">Initial value of the msrp property.</param>
        /// <param name="qoh">Initial value of the qoh property.</param>
        /// <param name="qob">Initial value of the qob property.</param>
        public static Product CreateProduct(global::System.String prodcd, global::System.String prodnam, global::System.String graphic, global::System.Decimal costprice, global::System.Decimal msrp, global::System.Int32 qoh, global::System.Int32 qob)
        {
            Product product = new Product();
            product.prodcd = prodcd;
            product.prodnam = prodnam;
            product.graphic = graphic;
            product.costprice = costprice;
            product.msrp = msrp;
            product.qoh = qoh;
            product.qob = qob;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prodcd
        {
            get
            {
                return _prodcd;
            }
            set
            {
                if (_prodcd != value)
                {
                    OnprodcdChanging(value);
                    ReportPropertyChanging("prodcd");
                    _prodcd = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("prodcd");
                    OnprodcdChanged();
                }
            }
        }
        private global::System.String _prodcd;
        partial void OnprodcdChanging(global::System.String value);
        partial void OnprodcdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prodnam
        {
            get
            {
                return _prodnam;
            }
            set
            {
                OnprodnamChanging(value);
                ReportPropertyChanging("prodnam");
                _prodnam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prodnam");
                OnprodnamChanged();
            }
        }
        private global::System.String _prodnam;
        partial void OnprodnamChanging(global::System.String value);
        partial void OnprodnamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String graphic
        {
            get
            {
                return _graphic;
            }
            set
            {
                OngraphicChanging(value);
                ReportPropertyChanging("graphic");
                _graphic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("graphic");
                OngraphicChanged();
            }
        }
        private global::System.String _graphic;
        partial void OngraphicChanging(global::System.String value);
        partial void OngraphicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal costprice
        {
            get
            {
                return _costprice;
            }
            set
            {
                OncostpriceChanging(value);
                ReportPropertyChanging("costprice");
                _costprice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("costprice");
                OncostpriceChanged();
            }
        }
        private global::System.Decimal _costprice;
        partial void OncostpriceChanging(global::System.Decimal value);
        partial void OncostpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal msrp
        {
            get
            {
                return _msrp;
            }
            set
            {
                OnmsrpChanging(value);
                ReportPropertyChanging("msrp");
                _msrp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("msrp");
                OnmsrpChanged();
            }
        }
        private global::System.Decimal _msrp;
        partial void OnmsrpChanging(global::System.Decimal value);
        partial void OnmsrpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qoh
        {
            get
            {
                return _qoh;
            }
            set
            {
                OnqohChanging(value);
                ReportPropertyChanging("qoh");
                _qoh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qoh");
                OnqohChanged();
            }
        }
        private global::System.Int32 _qoh;
        partial void OnqohChanging(global::System.Int32 value);
        partial void OnqohChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qob
        {
            get
            {
                return _qob;
            }
            set
            {
                OnqobChanging(value);
                ReportPropertyChanging("qob");
                _qob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qob");
                OnqobChanged();
            }
        }
        private global::System.Int32 _qob;
        partial void OnqobChanging(global::System.Int32 value);
        partial void OnqobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eStoreDBModel", "FK_ItemIsProduct", "OrderLineitems")]
        public EntityCollection<OrderLineitem> OrderLineitems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderLineitem>("eStoreDBModel.FK_ItemIsProduct", "OrderLineitems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderLineitem>("eStoreDBModel.FK_ItemIsProduct", "OrderLineitems", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="eStoreDBModel", Name="AllCustomerInfo")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class AllCustomerInfo : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MailCode
        {
            get
            {
                return _MailCode;
            }
            set
            {
                OnMailCodeChanging(value);
                ReportPropertyChanging("MailCode");
                _MailCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MailCode");
                OnMailCodeChanged();
            }
        }
        private global::System.String _MailCode;
        partial void OnMailCodeChanging(global::System.String value);
        partial void OnMailCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="eStoreDBModel", Name="GetThreeClosestBranches")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetThreeClosestBranches : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetThreeClosestBranches object.
        /// </summary>
        /// <param name="branchNumber">Initial value of the BranchNumber property.</param>
        public static GetThreeClosestBranches CreateGetThreeClosestBranches(global::System.Int32 branchNumber)
        {
            GetThreeClosestBranches getThreeClosestBranches = new GetThreeClosestBranches();
            getThreeClosestBranches.BranchNumber = branchNumber;
            return getThreeClosestBranches;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BranchNumber
        {
            get
            {
                return _BranchNumber;
            }
            set
            {
                OnBranchNumberChanging(value);
                ReportPropertyChanging("BranchNumber");
                _BranchNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BranchNumber");
                OnBranchNumberChanged();
            }
        }
        private global::System.Int32 _BranchNumber;
        partial void OnBranchNumberChanging(global::System.Int32 value);
        partial void OnBranchNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DistanceFromAddress
        {
            get
            {
                return _DistanceFromAddress;
            }
            set
            {
                OnDistanceFromAddressChanging(value);
                ReportPropertyChanging("DistanceFromAddress");
                _DistanceFromAddress = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DistanceFromAddress");
                OnDistanceFromAddressChanged();
            }
        }
        private Nullable<global::System.Double> _DistanceFromAddress;
        partial void OnDistanceFromAddressChanging(Nullable<global::System.Double> value);
        partial void OnDistanceFromAddressChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="eStoreDBModel", Name="SingleOrderDetails")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SingleOrderDetails : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SingleOrderDetails object.
        /// </summary>
        /// <param name="prodnam">Initial value of the prodnam property.</param>
        /// <param name="sellingPrice">Initial value of the SellingPrice property.</param>
        /// <param name="orderDate">Initial value of the OrderDate property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="qtysold">Initial value of the qtysold property.</param>
        /// <param name="qtyordered">Initial value of the qtyordered property.</param>
        /// <param name="qtybackordered">Initial value of the qtybackordered property.</param>
        public static SingleOrderDetails CreateSingleOrderDetails(global::System.String prodnam, global::System.Decimal sellingPrice, global::System.DateTime orderDate, global::System.Int32 orderID, global::System.Int32 qtysold, global::System.Int32 qtyordered, global::System.Int32 qtybackordered)
        {
            SingleOrderDetails singleOrderDetails = new SingleOrderDetails();
            singleOrderDetails.prodnam = prodnam;
            singleOrderDetails.SellingPrice = sellingPrice;
            singleOrderDetails.OrderDate = orderDate;
            singleOrderDetails.OrderID = orderID;
            singleOrderDetails.qtysold = qtysold;
            singleOrderDetails.qtyordered = qtyordered;
            singleOrderDetails.qtybackordered = qtybackordered;
            return singleOrderDetails;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prodnam
        {
            get
            {
                return _prodnam;
            }
            set
            {
                OnprodnamChanging(value);
                ReportPropertyChanging("prodnam");
                _prodnam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prodnam");
                OnprodnamChanged();
            }
        }
        private global::System.String _prodnam;
        partial void OnprodnamChanging(global::System.String value);
        partial void OnprodnamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SellingPrice
        {
            get
            {
                return _SellingPrice;
            }
            set
            {
                OnSellingPriceChanging(value);
                ReportPropertyChanging("SellingPrice");
                _SellingPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellingPrice");
                OnSellingPriceChanged();
            }
        }
        private global::System.Decimal _SellingPrice;
        partial void OnSellingPriceChanging(global::System.Decimal value);
        partial void OnSellingPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                OnOrderIDChanging(value);
                ReportPropertyChanging("OrderID");
                _OrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderID");
                OnOrderIDChanged();
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qtysold
        {
            get
            {
                return _qtysold;
            }
            set
            {
                OnqtysoldChanging(value);
                ReportPropertyChanging("qtysold");
                _qtysold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtysold");
                OnqtysoldChanged();
            }
        }
        private global::System.Int32 _qtysold;
        partial void OnqtysoldChanging(global::System.Int32 value);
        partial void OnqtysoldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qtyordered
        {
            get
            {
                return _qtyordered;
            }
            set
            {
                OnqtyorderedChanging(value);
                ReportPropertyChanging("qtyordered");
                _qtyordered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtyordered");
                OnqtyorderedChanged();
            }
        }
        private global::System.Int32 _qtyordered;
        partial void OnqtyorderedChanging(global::System.Int32 value);
        partial void OnqtyorderedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qtybackordered
        {
            get
            {
                return _qtybackordered;
            }
            set
            {
                OnqtybackorderedChanging(value);
                ReportPropertyChanging("qtybackordered");
                _qtybackordered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtybackordered");
                OnqtybackorderedChanged();
            }
        }
        private global::System.Int32 _qtybackordered;
        partial void OnqtybackorderedChanging(global::System.Int32 value);
        partial void OnqtybackorderedChanged();

        #endregion

    }

    #endregion

    
}
